import type { Express, Request, Response } from 'express';
import {
  adb,
  adbWithLimits,
  diagnosticSnapshot,
  logcatErrors,
  logcatWarnings,
} from '../adb';
import { parseGetpropOutput } from '../utils';
import {
  analyzeBattery,
  analyzeBatteryConnection,
  analyzeBatteryConnectionSeries,
  analyzeLogs,
  analyzeMemoryHealth,
  analyzeRadioModemStability,
  analyzeStorage,
  analyzeThermalThrottling,
  analyzeUsbInstability,
  inferShutdownCause,
} from '../heuristics';
import { beginMobileDiagnostic, endMobileDiagnostic } from '../serverContext';
import {
  type DiagDetails,
  type SavedRun,
  type StageSummary,
} from '../lib/historyStore';
import { saveDiagnosticRunToCloud } from '../lib/supabaseDiagnosticsStore';

// Best-effort helper to load the on-device JSON report generated by the
// SmartHub Mobile Diagnostics app. This reads from the app's external
// files directory so it works without root.
async function loadOnDeviceReport(deviceId: string): Promise<{ path: string; json: any } | undefined> {
  const pkg = 'com.smarthub.diagnostics';
  const fileName = 'smarthub_diagnostics.json';
  const candidatePaths = [
    `/sdcard/Android/data/${pkg}/files/${fileName}`,
    `/storage/emulated/0/Android/data/${pkg}/files/${fileName}`,
  ];

  for (const p of candidatePaths) {
    try {
      const out = await adb('-s', deviceId, 'shell', 'cat', p);
      const trimmed = (out || '').trim();
      if (!trimmed) continue;
      try {
        const parsed = JSON.parse(trimmed);
        return { path: p, json: parsed };
      } catch (e: any) {
        // eslint-disable-next-line no-console
        console.error('loadOnDeviceReport: failed to parse JSON from', p, e);
        continue;
      }
    } catch {
      // File may not exist on this path; try the next candidate.
      continue;
    }
  }

  return undefined;
}

type FindingLike = {
  id?: string;
  title?: string;
  severity?: string;
  details?: string;
};

function buildCollectDeviceLabel(deviceId: string, props: Record<string, string>): string {
  const manufacturer =
    props['ro.product.manufacturer'] ||
    props['ro.product.system.manufacturer'] ||
    props['ro.product.vendor.manufacturer'] ||
    props['ro.product.odm.manufacturer'] ||
    props['ro.product.brand'];
  const model =
    props['ro.product.model'] ||
    props['ro.product.system.model'] ||
    props['ro.product.vendor.model'] ||
    props['ro.product.odm.model'] ||
    props['ro.product.name'];
  const combined = [manufacturer, model].filter(Boolean).join(' ').trim();
  return combined || deviceId;
}

function countFindingsBySeverity(findings: FindingLike[]): { high: number; medium: number; low: number } {
  let high = 0;
  let medium = 0;
  let low = 0;
  for (const f of findings) {
    const sev = String(f?.severity || 'low').toLowerCase();
    if (sev === 'high') high += 1;
    else if (sev === 'medium') medium += 1;
    else low += 1;
  }
  return { high, medium, low };
}

function buildCollectTextReport(findings: FindingLike[]): string {
  if (!Array.isArray(findings) || findings.length === 0) {
    return 'No major findings reported.';
  }

  const blocks = findings.slice(0, 120).map((f) => {
    const sev = String(f?.severity || 'low').toLowerCase();
    const sevLabel = sev === 'high' ? 'High' : sev === 'medium' ? 'Medium' : 'Low';
    const title = String(f?.title || f?.id || 'Diagnostic finding').trim();
    const details = String(f?.details || '').trim();
    return details
      ? `${title} [${sevLabel}]\n- ${details}`
      : `${title} [${sevLabel}]`;
  });

  return blocks.join('\n\n');
}

async function autoSaveCollectResultToHistory(params: {
  ownerUserId?: string;
  deviceId: string;
  deviceLabel: string;
  findings: FindingLike[];
  diagStages: Record<string, StageSummary>;
  diagDetails: DiagDetails;
  textReport: string;
}): Promise<{ runId: number }> {
  const ownerUserId = String(params.ownerUserId || '').trim();
  if (!ownerUserId) {
    throw new Error('Authenticated Supabase account required. Local/offline history is disabled.');
  }

  const now = Date.now();
  const counts = countFindingsBySeverity(params.findings);

  const run: SavedRun = {
    id: now,
    deviceId: params.deviceId,
    deviceLabel: params.deviceLabel,
    timestamp: now,
    counts,
    diagStages: params.diagStages,
    diagDetails: params.diagDetails,
    textReport: params.textReport,
  };

  const cloud = await saveDiagnosticRunToCloud({
    ownerUserId,
    diagnosticType: 'history',
    deviceId: params.deviceId,
    runId: run.id,
    runTimestamp: run.timestamp,
    payload: run,
  });
  if (!cloud.ok) {
    throw new Error(cloud.error || 'Failed to save collect result to Supabase.');
  }

  return { runId: run.id };
}

export function registerCollectRoutes(app: Express): void {
  app.get('/collect/:id', async (req: Request, res: Response) => {
    const id = req.params.id;
    try {
      await beginMobileDiagnostic(id);

      // Use a single batched ADB snapshot to reduce USB/ADB churn.
      const snap = await diagnosticSnapshot(id);
      const propsDump = snap.propsDump;
      const batteryDump = snap.batteryDump;
      const batteryDump2 = snap.batteryDump2;
      const batteryDump3 = snap.batteryDump3;
      const storageDump = snap.storageDump;
      const memInfoDump = snap.memInfoDump;
      const displayDump = snap.displayDump;
      const wmSizeDump = snap.wmSizeDump;
      const wmDensityDump = snap.wmDensityDump;
      const cpuInfoDump = snap.cpuInfoDump;
      const logs = await logcatErrors(id);
      const warnLogs = await logcatWarnings(id);

      // Best-effort shutdown/reboot evidence. These are intentionally time/buffer bounded,
      // and are allowed to fail silently (many OEM builds restrict kernel/crash buffers).
      let crashLogs = '';
      let kernelLogs = '';
      let powerDump = '';
      let thermalDump = '';

      try {
        crashLogs = await adbWithLimits(
          ['-s', id, 'logcat', '-d', '-v', 'time', '-b', 'crash', '*:E'],
          { timeoutMs: 10_000, maxBufferBytes: 2 * 1024 * 1024, attempts: 1 },
        );
      } catch {
        crashLogs = '';
      }

      try {
        kernelLogs = await adbWithLimits(
          ['-s', id, 'logcat', '-d', '-v', 'time', '-b', 'kernel', '*:W'],
          { timeoutMs: 10_000, maxBufferBytes: 2 * 1024 * 1024, attempts: 1 },
        );
      } catch {
        kernelLogs = '';
      }

      try {
        powerDump = await adbWithLimits(
          ['-s', id, 'shell', 'dumpsys', 'power'],
          { timeoutMs: 12_000, maxBufferBytes: 4 * 1024 * 1024, attempts: 1 },
        );
      } catch {
        powerDump = '';
      }

      try {
        thermalDump = await adbWithLimits(
          ['-s', id, 'shell', 'dumpsys', 'thermalservice'],
          { timeoutMs: 12_000, maxBufferBytes: 4 * 1024 * 1024, attempts: 1 },
        );
      } catch {
        thermalDump = '';
      }

      if (!thermalDump) {
        try {
          thermalDump = await adbWithLimits(
            ['-s', id, 'shell', 'dumpsys', 'thermal'],
            { timeoutMs: 12_000, maxBufferBytes: 4 * 1024 * 1024, attempts: 1 },
          );
        } catch {
          thermalDump = '';
        }
      }

      const batteryConnectionFindings = batteryDump3
        ? analyzeBatteryConnectionSeries([batteryDump, batteryDump2, batteryDump3])
        : analyzeBatteryConnection(batteryDump, batteryDump2);

      const findings = [
        ...analyzeBattery(batteryDump),
        ...batteryConnectionFindings,
        ...analyzeStorage(storageDump),
        ...analyzeMemoryHealth(memInfoDump),
        ...analyzeLogs(logs),
        ...analyzeUsbInstability({ logs, warnLogs, kernelLogs }),
        ...analyzeThermalThrottling(thermalDump, logs, warnLogs),
        ...analyzeRadioModemStability({ logs, warnLogs, crashLogs, kernelLogs }),
      ];

      // Battery chemistry/type: prefer dumpsys, fall back to common sysfs paths and drop placeholder values like "0"/"unknown".
      const normalizeBatteryTech = (raw?: string): string | undefined => {
        if (!raw) return undefined;
        const val = raw.trim();
        if (!val) return undefined;
        const lower = val.toLowerCase();
        if (lower === 'unknown' || lower === 'n/a' || lower === 'na' || lower === 'none') return undefined;
        if (/^0+$/.test(val) || /^-1$/.test(val)) return undefined;
        return val;
      };

      let batteryTechnology: string | undefined;
      const techMatch = batteryDump.match(/technology:\s*(.+)/i);
      if (techMatch?.[1]) {
        batteryTechnology = normalizeBatteryTech(techMatch[1]);
      }

      if (!batteryTechnology) {
        const techPaths = [
          '/sys/class/power_supply/battery/technology',
          '/sys/class/power_supply/battery/type',
          '/sys/class/power_supply/battery/chemistry',
          '/sys/class/power_supply/bms/technology',
          '/sys/class/power_supply/bms/type',
          '/sys/class/power_supply/bms/chemistry',
          '/sys/class/power_supply/max170xx_battery/technology',
        ];

        for (const p of techPaths) {
          try {
            const techOut = await adb('-s', id, 'shell', 'cat', p);
            const techStr = (techOut || '').trim().split(/\s+/)[0];
            const norm = normalizeBatteryTech(techStr);
            if (norm) {
              batteryTechnology = norm;
              break;
            }
          } catch {
            // ignore – not all devices expose these paths
          }
        }
      }

      const props: Record<string, string> = parseGetpropOutput(propsDump);

      // Basic OS build information
      let androidVersion: string | undefined;
      let buildFingerprint: string | undefined;
      let isCustomBuild: boolean | undefined;
      let verifiedBootState: string | undefined;
      let bootloaderLocked: boolean | undefined;
      androidVersion = props['ro.build.version.release'] || props['ro.build.version.release_or_codename'] || undefined;
      buildFingerprint = props['ro.build.fingerprint'] || undefined;

      const tags = props['ro.build.tags'];
      if (tags && /test-keys/i.test(tags)) {
        isCustomBuild = true;
      }

      verifiedBootState = props['ro.boot.verifiedbootstate'] || undefined;

      const lockedVal = props['ro.boot.flash.locked'];
      if (lockedVal === '0') bootloaderLocked = false;
      else if (lockedVal === '1') bootloaderLocked = true;

      let displayWidth: number | undefined;
      let displayHeight: number | undefined;

      const logicalMatch = displayDump.match(/logicalWidth=(\d+),\s*logicalHeight=(\d+)/);
      if (logicalMatch) {
        displayWidth = Number(logicalMatch[1]);
        displayHeight = Number(logicalMatch[2]);
      } else {
        const deviceInfoMatch = displayDump.match(/DisplayDeviceInfo\{\".*?\".*?width=(\d+), height=(\d+)/);
        if (deviceInfoMatch) {
          displayWidth = Number(deviceInfoMatch[1]);
          displayHeight = Number(deviceInfoMatch[2]);
        }
      }

      // Fallback: wm size is often available even when dumpsys display is partial.
      if ((!displayWidth || !displayHeight) && typeof wmSizeDump === 'string' && wmSizeDump.trim()) {
        const m = wmSizeDump.match(/(Override size|Physical size):\s*(\d+)x(\d+)/i);
        if (m?.[2] && m?.[3]) {
          const w = Number(m[2]);
          const h = Number(m[3]);
          if (!Number.isNaN(w) && !Number.isNaN(h) && w > 0 && h > 0) {
            displayWidth = w;
            displayHeight = h;
          }
        }
      }

      let diagonalInches: number | undefined;
      let areaCm2: number | undefined;

      // Approximate physical size if we can find a DPI value in dumpsys display
      // or from density properties (ro.sf.lcd_density, etc.).
      if (displayWidth && displayHeight) {
        let dpi: number | undefined;

        const dpiMatch = displayDump.match(/(\d+)dpi/);
        if (dpiMatch?.[1]) {
          dpi = Number(dpiMatch[1]);
        }

        if (!dpi || Number.isNaN(dpi) || dpi <= 0) {
          // Prefer wm density when present.
          if (typeof wmDensityDump === 'string' && wmDensityDump.trim()) {
            const dm = wmDensityDump.match(/(Override density|Physical density):\s*(\d+)/i);
            if (dm?.[2]) {
              const d = Number(dm[2]);
              if (!Number.isNaN(d) && d > 0) dpi = d;
            }
          }

          if (!dpi || Number.isNaN(dpi) || dpi <= 0) {
            const lcd = props['ro.sf.lcd_density'] || props['ro.display.lcd_density'];
            if (lcd) dpi = Number(lcd);
          }
        }

        if (dpi && !Number.isNaN(dpi) && dpi > 0) {
          const diagPx = Math.sqrt(displayWidth * displayWidth + displayHeight * displayHeight);
          const diagIn = diagPx / dpi;
          const widthIn = displayWidth / dpi;
          const heightIn = displayHeight / dpi;
          const areaIn2 = widthIn * heightIn;
          const areaCm = areaIn2 * 6.4516;

          diagonalInches = Math.round(diagIn * 10) / 10;
          areaCm2 = Math.round(areaCm * 10) / 10;
        }
      }

      const batteryMeta = batteryTechnology ? { technology: batteryTechnology } : undefined;
      const displayMeta = displayWidth && displayHeight
        ? { width: displayWidth, height: displayHeight, diagonalInches, areaCm2 }
        : undefined;

      // Extra dumps are already included in the batched snapshot.
      const sensorsDump = snap.sensorsDump;
      const cameraDump = snap.cameraDump;
      const connectivityDump = snap.connectivityDump;
      const featuresDump = snap.featuresDump;

      const diagStages: Record<string, StageSummary> = {};
      const diagDetails: DiagDetails = {};

      // Battery stage
      if (batteryDump) {
        const levelMatch = batteryDump.match(/level:\s*(\d+)/i);
        const tempMatch = batteryDump.match(/temperature:\s*(\d+)/i);
        const healthMatch = batteryDump.match(/health:\s*([^\r\n]+)/i);
        const presentMatch = batteryDump.match(/present:\s*(true|false)/i);
        const voltageMatch = batteryDump.match(/voltage:\s*(-?\d+)/i);
        const currentMatch = batteryDump.match(/current now:\s*(-?\d+)/i);
        const statusLine = batteryDump.match(/status:\s*([^\r\n]+)/i);

        const level = levelMatch ? Number(levelMatch[1]) : undefined;
        const tempRaw = tempMatch ? Number(tempMatch[1]) : undefined;
        const tempC = typeof tempRaw === 'number' && !Number.isNaN(tempRaw) ? tempRaw / 10 : undefined;
        const normalizeBatteryHealth = (raw?: string): string | undefined => {
          if (!raw) return undefined;
          const token = raw.trim().split(/\s+/)[0];
          if (!token) return undefined;
          const asNum = Number(token);
          if (!Number.isNaN(asNum) && Number.isFinite(asNum)) {
            // Android BatteryManager health constants.
            switch (asNum) {
              case 1:
                return 'Unknown';
              case 2:
                return 'Good';
              case 3:
                return 'Overheat';
              case 4:
                return 'Dead';
              case 5:
                return 'Over-voltage';
              case 6:
                return 'Failure';
              case 7:
                return 'Cold';
              default:
                return 'Unknown';
            }
          }
          return token;
        };

        const health = normalizeBatteryHealth(healthMatch?.[1]);

        const present = presentMatch?.[1] ? presentMatch[1].toLowerCase() === 'true' : undefined;
        const voltageMv = voltageMatch?.[1] ? Number(voltageMatch[1]) : undefined;
        const currentNowRaw = currentMatch?.[1] ? Number(currentMatch[1]) : undefined;
        const statusToken = statusLine?.[1] ? statusLine[1].trim().split(/\s+/)[0] : undefined;

        const isCharging = /AC powered:\s*true/i.test(batteryDump) ||
          /USB powered:\s*true/i.test(batteryDump) ||
          /Wireless powered:\s*true/i.test(batteryDump) ||
          statusToken === '2' ||
          statusToken === '5';

        // Extract power/battery warnings that often indicate an intermittent connector,
        // undervoltage, PMIC reset, or thermal/power-path shutdown.
        // NOTE: Keep this STRICT to avoid false positives on generic "power" words.
        const mergedLogs = `${logs || ''}\n${warnLogs || ''}`;

        const strongPowerPatterns: Array<{ rx: RegExp; points: number }> = [
          { rx: /\b(uvlo|undervoltage|under-voltage|brownout)\b/i, points: 3 },
          { rx: /\b(pmic|pmu|vbat|vbatt|vsys)\b/i, points: 3 },
          { rx: /\b(reset\s*reason|reboot\s*reason|shutdown\s*reason|boot\s*reason)\b/i, points: 3 },
          { rx: /\b(unexpected\s*shutdown|sudden\s*shutdown)\b/i, points: 3 },
          { rx: /\b(battery\s*disconnect|battery\s*removed)\b/i, points: 3 },
        ];

        const mediumPowerPatterns: Array<{ rx: RegExp; points: number }> = [
          { rx: /\bhealthd\b/i, points: 1 },
          { rx: /\bBatteryService\b/i, points: 1 },
          { rx: /\b(power_supply|charger|charging|vbus)\b/i, points: 1 },
          { rx: /\b(thermal\s*shutdown|overheat\s*shutdown|thermal)\b/i, points: 2 },
        ];

        const allPatterns = [...strongPowerPatterns, ...mediumPowerPatterns];
        const scored: Array<{ line: string; score: number }> = [];

        for (const rawLine of mergedLogs.split(/\r?\n/)) {
          const line = rawLine.trim();
          if (!line) continue;
          let lineScore = 0;
          for (const { rx, points } of allPatterns) {
            if (rx.test(line)) lineScore += points;
          }
          if (lineScore > 0) scored.push({ line, score: lineScore });
        }

        const powerLogScore = scored.reduce((sum, item) => sum + item.score, 0);
        const powerLogSuspected = powerLogScore >= 4; // stricter threshold

        const powerLogHints = scored
          .sort((a, b) => b.score - a.score)
          .slice(0, 20)
          .map(s => s.line);

        let capacityMah: number | undefined;
        const capMatch = batteryDump.match(/capacity:\s*(\d+)/i);
        if (capMatch?.[1]) {
          capacityMah = Number(capMatch[1]);
        } else {
          // dumpsys battery often uses "Charge counter:" (µAh) not "charge_counter:".
          const chargeMatch = batteryDump.match(/charge[_\s]*counter:\s*(\d+)/i);
          if (chargeMatch?.[1]) {
            const raw = Number(chargeMatch[1]);
            if (!Number.isNaN(raw) && raw > 0) {
              // Common convention: value in µAh.
              const approxMah = raw > 5000 ? Math.round(raw / 1000) : raw;
              capacityMah = approxMah;
            }
          }
        }

        // Normalize obviously-wrong values.
        if (typeof capacityMah === 'number' && (!Number.isFinite(capacityMah) || capacityMah <= 0)) {
          capacityMah = undefined;
        }
        if (typeof capacityMah === 'number' && (capacityMah < 200 || capacityMah > 20000)) {
          // Outside realistic phone battery range; treat as not reported.
          capacityMah = undefined;
        }

        // Best-effort fallback: some devices only expose design/full capacity via sysfs.
        if (capacityMah === undefined) {
          const capPaths = [
            '/sys/class/power_supply/battery/charge_full_design',
            '/sys/class/power_supply/battery/charge_full',
            '/sys/class/power_supply/bms/charge_full_design',
            '/sys/class/power_supply/bms/charge_full',
            '/sys/class/power_supply/battery/energy_full_design',
            '/sys/class/power_supply/battery/energy_full',
            '/sys/class/power_supply/bms/energy_full_design',
            '/sys/class/power_supply/bms/energy_full',
          ];

          for (const p of capPaths) {
            try {
              const out = await adb('-s', id, 'shell', 'cat', p);
              const token = (out || '').trim().split(/\s+/)[0];
              const val = Number(token);
              if (Number.isNaN(val) || val <= 0) continue;
              const approxMah = val > 5000 ? Math.round(val / 1000) : val;
              if (approxMah >= 200 && approxMah <= 20000) {
                capacityMah = approxMah;
                break;
              }
            } catch {
              // ignore
            }
          }
        }

        // Last-resort fallback: batterystats sometimes exposes an estimated mAh value.
        // This can be large on some devices, so keep it bounded and best-effort.
        if (capacityMah === undefined) {
          try {
            const bs = await adbWithLimits(
              ['-s', id, 'shell', 'dumpsys', 'batterystats'],
              { timeoutMs: 12_000, maxBufferBytes: 3 * 1024 * 1024, attempts: 1 },
            );
            const m = (bs || '').match(/Estimated\s+battery\s+capacity:\s*(\d+)\s*mAh/i);
            if (m?.[1]) {
              const val = Number(m[1]);
              if (!Number.isNaN(val) && val >= 200 && val <= 20000) {
                capacityMah = val;
              }
            }
          } catch {
            // ignore
          }
        }

        let cycleCount: number | undefined;
        const cycleMatch = batteryDump.match(/cycle[_\s]*count:\s*(\d+)/i);
        if (cycleMatch?.[1]) {
          cycleCount = Number(cycleMatch[1]);
        }

        if (cycleCount === undefined) {
          const cyclePaths = [
            '/sys/class/power_supply/battery/cycle_count',
            '/sys/class/power_supply/bms/cycle_count',
            '/sys/class/power_supply/battery/cyclecount',
            '/sys/class/power_supply/bms/cyclecount',
          ];

          for (const p of cyclePaths) {
            try {
              const cycleOut = await adb('-s', id, 'shell', 'cat', p);
              const cycleStr = (cycleOut || '').trim().split(/\s+/)[0];
              const cycleVal = Number(cycleStr);
              if (!Number.isNaN(cycleVal) && cycleVal >= 0) {
                cycleCount = cycleVal;
                break;
              }
            } catch {
              // ignore
            }
          }
        }

        const parts: string[] = [];
        if (batteryTechnology) parts.push(`Type ${batteryTechnology}`);
        if (typeof level === 'number') parts.push(`Level ${level}%`);
        if (typeof tempC === 'number') parts.push(`Temp ${tempC.toFixed(1)}°C`);
        if (health) parts.push(`Health ${health}`);
        if (typeof voltageMv === 'number' && Number.isFinite(voltageMv) && voltageMv > 0) parts.push(`Voltage ${voltageMv}mV`);

        const hasConnectionFinding = findings.some(f => f && f.id === 'battery-connection' && (f.severity === 'medium' || f.severity === 'high'));
        const thermalFinding = findings.find(f => f && f.id === 'thermal-throttling' && (f.severity === 'medium' || f.severity === 'high'));
        if (thermalFinding) parts.push('Thermal throttling evidence');

        let ok = true;
        if (typeof level === 'number' && level < 20) ok = false;
        if (typeof tempC === 'number' && tempC > 45) ok = false;
        if (health && !/good|unknown/i.test(health)) ok = false;
        if (hasConnectionFinding) ok = false;
        if (thermalFinding) ok = false;

        let chargingEfficiency: string | undefined;
        if (typeof tempC === 'number') {
          if (tempC <= 40 && (!health || /good|unknown/i.test(health))) {
            chargingEfficiency = 'Normal efficiency';
          } else if (tempC > 45 || (health && !/good|unknown/i.test(health))) {
            chargingEfficiency = 'Reduced efficiency (heat or wear)';
          }
        }

        diagStages.battery = {
          ok,
          label: ok
            ? 'Battery looks healthy'
            : hasConnectionFinding
              ? 'Possible battery/power connection issue'
              : thermalFinding
                ? 'Thermal / overheating warning'
                : 'Battery warning',
          details: parts.join(' · ') || undefined,
        };

        diagDetails.battery = {
          name: batteryTechnology,
          level,
          temperatureC: tempC,
          health,
          capacityMah,
          cycleCount,
          chargingEfficiency,
          present,
          voltageMv: typeof voltageMv === 'number' && Number.isFinite(voltageMv) ? voltageMv : undefined,
          currentNowRaw: typeof currentNowRaw === 'number' && Number.isFinite(currentNowRaw) ? currentNowRaw : undefined,
          status: statusToken,
          isCharging,
          connectionSuspected: hasConnectionFinding || undefined,
          powerLogSuspected: powerLogSuspected || undefined,
          powerLogScore: powerLogSuspected ? powerLogScore : undefined,
          powerLogHints: powerLogSuspected ? powerLogHints : undefined,
        };
      }

      // Display & logs stage
      const displayIssueFinding = findings.find(f =>
        f.id === 'display-pipeline' && (f.severity === 'medium' || f.severity === 'high')
      );
      const hasDisplayIssue = !!displayIssueFinding;
      const displayIssueReason = hasDisplayIssue
        ? ((displayIssueFinding && typeof displayIssueFinding.details === 'string' && displayIssueFinding.details.trim())
            ? displayIssueFinding.details.trim()
            : (displayIssueFinding && typeof displayIssueFinding.title === 'string' && displayIssueFinding.title.trim())
              ? displayIssueFinding.title.trim()
              : 'Display pipeline warning detected in logs.')
        : '';

      const displayDetailParts: string[] = [];
      if (displayMeta?.width && displayMeta.height) {
        displayDetailParts.push(`${displayMeta.width} x ${displayMeta.height} px`);
        if (typeof displayMeta.diagonalInches === 'number') {
          displayDetailParts.push(`${displayMeta.diagonalInches.toFixed(1)}" approx`);
        }
      }
      if (displayIssueReason) {
        displayDetailParts.push(`Log signal: ${displayIssueReason}`);
      }
      const displayDetails: string | undefined = displayDetailParts.length
        ? displayDetailParts.join(' · ')
        : undefined;

      diagStages.display = {
        ok: !hasDisplayIssue,
        label: hasDisplayIssue ? 'Display/log pipeline issues' : 'Display pipeline OK',
        details: displayDetails,
      };

      if (displayMeta) {
        diagDetails.display = {
          width: displayMeta.width,
          height: displayMeta.height,
          diagonalInches: displayMeta.diagonalInches,
          areaCm2: displayMeta.areaCm2,
          issueReason: displayIssueReason || undefined,
        };
      }

      // Touch / ghost touch heuristics stage - based on logcat and charging state.
      // This stage must always reach a final state so the UI doesn't show
      // results while the touch step is still "Diagnosting…".
      try {
        let hasTouchDriverErrors = false;
        let hasInputAnomalies = false;
        let isChargingDuringLogs = false;

        if (logs) {
          if (/(touchpanel|fts|synaptics|goodix|elan|atmel).*error/i.test(logs) ||
            /InputReader.*(failed|error|not responding)/i.test(logs)) {
            hasTouchDriverErrors = true;
          }

          if (/InputDispatcher.*channel.*unresponsive/i.test(logs) ||
            /pointer .*cancel/i.test(logs) ||
            /touch event rate too high/i.test(logs)) {
            hasInputAnomalies = true;
          }
        }

        if (batteryDump) {
          if (/AC powered:\s*true/i.test(batteryDump) ||
            /USB powered:\s*true/i.test(batteryDump) ||
            /status:\s*(2|3)/i.test(batteryDump)) {
            isChargingDuringLogs = true;
          }
        }

        const touchIssues: string[] = [];
        if (hasTouchDriverErrors) {
          touchIssues.push('Touch controller or driver reported errors in logs');
        }
        if (hasInputAnomalies) {
          touchIssues.push('Input system reported abnormal touch or pointer behaviour');
        }
        if (!hasTouchDriverErrors && !hasInputAnomalies) {
          touchIssues.push('No clear touch-driver or input anomalies seen in recent logs');
        }
        if (isChargingDuringLogs) {
          touchIssues.push('Device was charging; ghost touch can worsen with bad cables/chargers');
        }

        const touchOk = !hasTouchDriverErrors && !hasInputAnomalies;
        const touchDetails = touchIssues.join(' · ');
        diagStages.touch = {
          ok: touchOk,
          label: touchOk ? 'No clear touch-driver or input anomalies' : 'Possible touch / ghost touch issues',
          details: touchDetails || undefined,
        };

        diagDetails.touch = {
          hasTouchDriverErrors,
          hasInputAnomalies,
          isChargingDuringLogs,
        };
      } catch {
        // best-effort only
      }

      // Sensors stage - check that sensorservice responds and lists sensors
      if (sensorsDump) {
        const lines = sensorsDump.split(/\r?\n/);
        const sensorLines = lines.filter(l => /sensor/i.test(l) && (/handle=/i.test(l) || /Sensor\s/i.test(l)));
        const count = sensorLines.length;
        const ok = count > 0;
        diagStages.sensors = {
          ok,
          label: ok ? 'Sensor service responding' : 'No sensor list available',
          details: ok ? `Detected ~${count} sensor entries` : undefined,
        };

        const hasAccelerometer = /accelerometer/i.test(sensorsDump);
        const hasGyroscope = /gyro/i.test(sensorsDump);
        const hasBarometer = /barometer/i.test(sensorsDump);
        const hasMagnetometer = /magnetometer|compass/i.test(sensorsDump);
        const hasProximitySensor = /proximity/i.test(sensorsDump);
        diagDetails.sensors = {
          sensorCount: count,
          hasAccelerometer,
          hasGyroscope,
          hasBarometer,
          hasMagnetometer,
          hasProximitySensor,
        };
      }

      // Camera & microphone stage - basic camera service presence
      if (cameraDump) {
        const lines = cameraDump.split(/\r?\n/);
        const camLines = lines.filter(l => /Camera ID|Camera device|camera\s+info/i.test(l));
        const count = camLines.length;
        const ok = count > 0;
        diagStages.camera = {
          ok,
          label: ok ? 'Camera service responding' : 'No camera service info',
          details: ok ? `Camera descriptors: ${count}` : undefined,
        };

        diagDetails.camera = {
          descriptorCount: count,
        };
      }

      // Connectivity stage - combine dumpsys connectivity with advertised hardware features
      if (connectivityDump || featuresDump) {
        const hasWifi = /WIFI/i.test(connectivityDump);
        const hasMobileStack = /MOBILE/i.test(connectivityDump);
        const hasTelephonyFeature = /android\.hardware\.telephony/i.test(featuresDump);
        const hasMobile = !!(hasMobileStack || hasTelephonyFeature);
        const ok = !!(hasWifi || hasMobile);
        const parts: string[] = [];
        if (hasWifi) parts.push('Wi‑Fi stack present');
        if (hasMobile) parts.push('Mobile data stack present');
        diagStages.connectivity = {
          ok,
          label: ok ? 'Connectivity services responding' : 'No connectivity info',
          details: parts.join(' · ') || undefined,
        };

        const hasBluetooth = /bluetooth/i.test(connectivityDump);
        const hasNfc = /nfc/i.test(connectivityDump);
        const hasGpsFeature = /android\.hardware\.location\.gps/i.test(featuresDump);
        const hasGpsFromConn = /gps/i.test(connectivityDump);
        const hasGps = !!(hasGpsFeature || hasGpsFromConn);
        diagDetails.connectivity = {
          hasWifi,
          hasBluetooth,
          hasNfc,
          hasGps,
          hasMobile,
        };

        // Additional ADB-only connectivity problems.
        const usbUnstable = findings.find(f => f && f.id === 'usb-instability' && (f.severity === 'medium' || f.severity === 'high'));
        const radioUnstable = findings.find(f => f && f.id === 'radio-modem-instability' && (f.severity === 'medium' || f.severity === 'high'));
        if (usbUnstable || radioUnstable) {
          const hints: string[] = [];
          if (usbUnstable) hints.push('ADB/USB disconnect instability seen in logs');
          if (radioUnstable) hints.push('Radio/modem crash/restart hints seen in logs');
          const existing = diagStages.connectivity.details;
          diagStages.connectivity.ok = false;
          diagStages.connectivity.label = usbUnstable ? 'Possible USB/connection instability' : 'Connectivity stability warnings';
          diagStages.connectivity.details = existing ? `${existing} · ${hints.join(' · ')}` : hints.join(' · ');
        }
      }

      // Hardware components stage - based on advertised features
      if (featuresDump) {
        const lines = featuresDump.split(/\r?\n/).filter(l => l.trim().length > 0);
        const hasFingerprint = /android\.hardware\.fingerprint/i.test(featuresDump);
        const hasNfc = /android\.hardware\.nfc/i.test(featuresDump);
        const hasAccel = /android\.hardware\.sensor\.accelerometer/i.test(featuresDump);
        const hasGyro = /android\.hardware\.sensor\.gyroscope/i.test(featuresDump);
        const hasMic = /android\.hardware\.microphone/i.test(featuresDump);
        const hasSpeaker = /android\.hardware\.audio\.output/i.test(featuresDump);
        const hasProxSensor = /android\.hardware\.sensor\.proximity/i.test(featuresDump);
        const parts: string[] = [];
        if (hasFingerprint) parts.push('Fingerprint');
        if (hasNfc) parts.push('NFC');
        if (hasAccel) parts.push('Accelerometer');
        if (hasGyro) parts.push('Gyroscope');
        const ok = lines.length > 0;
        diagStages.hardware = {
          ok,
          label: ok ? 'Core hardware features advertised' : 'No feature list available',
          details: parts.length ? parts.join(' · ') : undefined,
        };

        diagDetails.hardware = {
          hasFingerprint,
          hasNfc,
          hasAccelerometer: hasAccel,
          hasGyroscope: hasGyro,
          hasMicrophone: hasMic,
          hasSpeaker,
          hasProximitySensor: hasProxSensor,
        };
      }

      // System & performance stage - based on storage/log findings
      const hasStorageIssue = findings.some(f => f.id.startsWith('storage-pressure-') && (f.severity === 'medium' || f.severity === 'high'));
      const hasCrashIssue = findings.some(f => f.id === 'crash-anr' && (f.severity === 'medium' || f.severity === 'high'));
      const hasMemoryIssue = findings.some(f => (f.id === 'memory-low' || f.id === 'memory-tight') && (f.severity === 'medium' || f.severity === 'high'));
      const systemOk = !hasStorageIssue && !hasCrashIssue && !hasMemoryIssue;
      const sysParts: string[] = [];
      if (hasStorageIssue) sysParts.push('Storage near full');
      if (hasCrashIssue) sysParts.push('Recent crash/ANR in logs');
      if (hasMemoryIssue) sysParts.push('Memory pressure detected');
      if (!sysParts.length) sysParts.push('No critical storage or crash findings');
      diagStages.system = {
        ok: systemOk,
        label: systemOk ? 'System snapshot OK' : 'System/performance warnings',
        details: sysParts.join(' · '),
      };

      let memTotalKb: number | undefined;
      const memMatch = memInfoDump.match(/MemTotal:\s*(\d+) kB/i);
      if (memMatch?.[1]) {
        memTotalKb = Number(memMatch[1]);
      }

      diagDetails.system = {
        hasStorageIssue,
        hasCrashIssue,
        memTotalKb,
      };

      // OS / filesystem health stage – looks for signs that the
      // underlying Android image or filesystem may be damaged.
      const hasFsError = /EXT4-fs error|F2FS-fs error|I\/Vold.*fsck/i.test(logs);
      const hasVerityIssue = /dm-verity|verity.*corrupt/i.test(logs);
      const hasCoreServiceCrashes = /FATAL EXCEPTION.*system_server|FATAL EXCEPTION.*zygote/i.test(logs);

      const osOk = !hasFsError && !hasVerityIssue && !hasCoreServiceCrashes;
      const osParts: string[] = [];
      if (hasFsError) osParts.push('Filesystem errors reported in logs');
      if (hasVerityIssue) osParts.push('dm-verity or partition integrity warnings');
      if (hasCoreServiceCrashes) osParts.push('Core Android services (system_server/zygote) crashed');
      if (!osParts.length) osParts.push('No clear signs of OS or filesystem corruption in logs.');

      diagStages.os = {
        ok: osOk,
        label: osOk ? 'OS / filesystem look stable' : 'Possible OS or filesystem corruption',
        details: osParts.join(' · '),
      };

      const bootReason = props['sys.boot.reason'] || props['ro.boot.bootreason'] || props['ro.boot.boot_reason'] || props['persist.sys.boot.reason'] || undefined;
      const shutdown = inferShutdownCause({
        bootReason,
        logs,
        warnLogs,
        crashLogs,
        kernelLogs,
        powerDump,
        thermalDump,
        batteryDump,
      });

      const powerInstabilitySuspected =
        !!diagDetails.battery?.connectionSuspected ||
        !!diagDetails.battery?.powerLogSuspected ||
        findings.some(f => f && f.id === 'battery-connection' && (f.severity === 'medium' || f.severity === 'high'));

      const shutdownEvidence = shutdown?.evidence ? [...shutdown.evidence] : [];
      let shutdownSummary = shutdown?.summary;
      if (shutdown && (shutdown.category === 'watchdog' || shutdown.category === 'unknown') && powerInstabilitySuspected) {
        shutdownSummary = shutdown.category === 'watchdog'
          ? 'Watchdog/hang reboot hints were found (but power instability is also suspected).'
          : 'No reliable boot reason was accessible (but power instability is suspected).';
        shutdownEvidence.unshift('hint=powerInstabilitySuspected (loose battery connector / failing battery / PMIC / power path)');
      }

      if (shutdown && shutdown.category && (shutdown.category !== 'unknown' || powerInstabilitySuspected) && shutdownSummary) {
        osParts.unshift(`Shutdown/reboot hint: ${shutdownSummary}`);
        diagStages.os.details = osParts.join(' · ');
      }

      diagDetails.os = {
        hasFsError,
        hasVerityIssue,
        hasCoreServiceCrashes,
        androidVersion,
        buildFingerprint,
        isCustomBuild,
        verifiedBootState,
        bootloaderLocked,
        bootReason,
        shutdownCategory: shutdown?.category || undefined,
        shutdownSummary: shutdownSummary || undefined,
        shutdownEvidence: shutdownEvidence.length ? shutdownEvidence.slice(0, 12) : undefined,
      };

      // Best-effort: pull any on-device JSON report produced by the
      // SmartHub Mobile Diagnostics app and include it alongside the
      // ADB-based diagnostics for technicians who want a combined view.
      let onDeviceReport: any;
      try {
        const loaded = await loadOnDeviceReport(id);
        if (loaded) {
          onDeviceReport = {
            sourcePath: loaded.path,
            report: loaded.json,
          };

          // If the phone app reports frequent USB power toggles, surface it as a technician hint.
          const togglesLast2Min = Number(loaded.json?.powerStability?.usb?.togglesLast2Min);
          const looseUsb = !!loaded.json?.powerStability?.suspected?.looseUsbCableOrPort;
          if ((looseUsb || (Number.isFinite(togglesLast2Min) && togglesLast2Min >= 3)) && diagStages.connectivity) {
            const hint = 'Phone reports frequent USB power connect/disconnect (possible loose cable/port)';
            const existing = diagStages.connectivity.details;
            diagStages.connectivity.ok = false;
            diagStages.connectivity.label = 'Possible USB/connection instability';
            diagStages.connectivity.details = existing ? `${existing} · ${hint}` : hint;
          }
        }
      } catch (e: any) {
        // eslint-disable-next-line no-console
        console.error('collect: failed to load on-device report:', e);
      }

      let autoSavedHistory: { ok: boolean; runId?: number; error?: string } = { ok: false };
      try {
        const deviceLabel = buildCollectDeviceLabel(id, props);
        const saved = await autoSaveCollectResultToHistory({
          ownerUserId: String((req as any)?.authUser?.id || '').trim(),
          deviceId: id,
          deviceLabel,
          findings: findings as FindingLike[],
          diagStages,
          diagDetails,
          textReport: buildCollectTextReport(findings as FindingLike[]),
        });
        autoSavedHistory = { ok: true, runId: saved.runId };
      } catch (e: any) {
        // eslint-disable-next-line no-console
        console.error('collect auto-save failed:', e);
        autoSavedHistory = { ok: false, error: e?.message || 'Failed to auto-save collect result' };
      }

      res.json({
        propsDump,
        props,
        batteryDump,
        batteryDump2,
        batteryDump3,
        storageDump,
        memInfo: memInfoDump,
        displayDump,
        wmSizeDump,
        wmDensityDump,
        cpuInfoDump,
        batteryMeta,
        displayMeta,
        logs,
        warnLogs,
        findings,
        diagStages,
        diagDetails,
        onDeviceReport,
        autoSavedHistory,
      });
    } catch (e: any) {
      res.status(500).json({ error: e.message ?? 'Unknown error' });
    } finally {
      await endMobileDiagnostic(id);
    }
  });
}
