import { adb } from './adb';

// Best-effort helper to load the on-device JSON report generated by the
// SmartHub Mobile Diagnostics app. This reads from the app's external
// files directory so it works without root.
export async function loadOnDeviceReport(
  deviceId: string,
): Promise<{ path: string; json: any } | undefined> {
  const pkg = 'com.smarthub.diagnostics';
  const fileName = 'smarthub_diagnostics.json';
  const candidatePaths = [
    `/sdcard/Android/data/${pkg}/files/${fileName}`,
    `/storage/emulated/0/Android/data/${pkg}/files/${fileName}`,
  ];

  for (const p of candidatePaths) {
    try {
      const out = await adb('-s', deviceId, 'shell', 'cat', p);
      const trimmed = (out || '').trim();
      if (!trimmed) continue;
      try {
        const parsed = JSON.parse(trimmed);
        return { path: p, json: parsed };
      } catch (e: any) {
        // eslint-disable-next-line no-console
        console.error('loadOnDeviceReport: failed to parse JSON from', p, e);
        continue;
      }
    } catch {
      continue;
    }
  }

  return undefined;
}
